### ISSUE TITLE
What is elloapi and elloprovider difference?

### ISSUE THREAD

**Issue by rlam3** [ello/ello-ios#128]
What is elloapi and elloprovider difference? I'm a bit confused with how you are doing your authentication system with routing. Could you point out how expired tokens are to be treated?

**Comment by mitchellporter** [comment]
At a high level, `ElloAPI` describes the endpoints of the API, potential params needed for the request, etc. `ElloProvider` executes the actual API requests and handles the responses.

**Comment by steam** [comment]
Hi @rlam3, `ElloProvider` makes requests and handles responses. It collaborates with `ElloAPI` and a handful of other types to ensure that requests and responses are routed appropriately. When a request runs smoothly `ElloProvider` maps the serialized JSON response into domain objects, and hands them back to the service/caller that requested them.

Authentication happens when a request is made if the response is a 401. We use a nifty [state machine](https://github.com/ello/ello-ios/blob/master/Sources/Networking/AuthState.swift) that @colinta wrote to track the state of a requests authorization via `ElloProvider's` [attemptAuthentication](https://github.com/ello/ello-ios/blob/master/Sources/Networking/ElloProvider.swift#L126) function. Poke around `ElloProvider` to see how it is used.
