### ISSUE TITLE
Hashing contacts

### ISSUE THREAD

**Issue by mitchellporter** [ello/ello-ios#257]
Hey guys,

Was just looking through the codebase and sniffing some of the network traffic to learn more about how Ello utilizes the address book and contacts to make inviting and connecting with friends easier. Have some quick questions for you based on what I found.

First question is, why did you guys decide to only use email addresses? Is there a reason that you decided to stay away from phone numbers? I'm not looking for a ton of info, just curious what thought process went into this.

Second, where is the actual hashing of the emails taking place? I've been digging through the code but can't seem to pinpoint where the email addresses actually get hashed. Last but not least, what are you using to perform the hashing? I assumed you were using something like a port of `bcrypt` but after taking a quick look at your pods I couldn't find anything.

I'm curious about all of this because I'll be implementing similar functionality soon and have always been a big fan of this codebase and your work, so would love to hear any insight you could provide.

Thanks.

**Comment by colinta** [comment]
We use the hash of the email addresses to search our database for corresponding users, or to send an invite code via email, but since we don't have any kind of "invite via phone" feature (and we don't collect phone numbers), the phone number just isn't useful to us.

The hashing takes place just before we send it to our API.  The extension is in [`CryptoStringExtensions.swift`](https://github.com/ello/ello-ios/blob/master/Sources/Extensions/CryptoStringExtensions.swift), so search for `saltedSHA1String` and you'll find it.  Clue: it's in [`ElloAPI.swift`](https://github.com/ello/ello-ios/blob/0812d0a55ad09f7460c7bf8e8c5b7b2fddfbf2e7/Sources/Networking/ElloAPI.swift)!)

**Comment by colinta** [comment]
(obv we don't use the email hash to send emails - I mean if we don't find a user, *then* we send the email address to the API and send an invite email)

**Comment by jayzes** [comment]
FWIW, there's a similar set of logic on the backend that hashes the e-mail addresses for comparison. This is all to avoid shipping the user's entire address book to the server for analysis (and all of the privacy issues that entails) [a la Path](http://www.theverge.com/2012/2/8/2785217/path-ios-address-book-upload-ceo-apology).

**Comment by mitchellporter** [comment]
@colinta Thanks for the info and for pointing out the hashing code location, this all looks great.

>FWIW, there's a similar set of logic on the backend that hashes the e-mail addresses for comparison. This is all to avoid shipping the user's entire address book to the server for analysis (and all of the privacy issues that entails) a la Path.

@jayzes Funny that you mentioned Path... that whole fiasco has always stuck with me as a dev and made me try to be extra aware of potential security flaws and is the reason why I investigate things like this.

>FWIW, there's a similar set of logic on the backend that hashes the e-mail addresses for comparison. 

I've always performed hashing server-side as well, but what's the point of this email hashing on the backend if all email addresses being uploaded from the phone have already been hashed, or am I misunderstanding something?

**Comment by colinta** [comment]
We have to store the email hash so that we can `SELECT ... FROM user WHERE hash = %` and pass the value from the request.  Otherwise we'd have to hash all the users every time this request comes in - yikes.

**Comment by mitchellporter** [comment]
@colinta totally understand, the reason I was confused is because @jayzes comment made it sound like you needed to re-hash email addresses on the backend, when they have already been hashed before even leaving the user's phone.

**Comment by jayzes** [comment]
So we do hash them both places - on the server when users create accounts or update their e-mail addresses, and on the phone at the time we get access to the address book. The two places both use the same salt to ensure that the results are directly comparable. That way we're only ever sending hashes over the wire, to compare and find friends, rather than a big set of live e-mail addresses.

**Comment by mitchellporter** [comment]
@jayzes Awesome got it appreciate the clarification and thanks for the help!

**Comment by steam** [comment]
In addition to never sending the user's email addresses over the network is the added security benefit of Ello never receiving a bulk list of a user's contact's emails. We simply compare known hashes with the ones sent from the iOS app. Any emails that don't match are gibberish to us and the app user can rest assured that we're not able to store or make use of real email addresses. The bulk lookup is separate from the user inviting contacts that don't have an existing Ello account.

**Comment by mitchellporter** [comment]
@steam thanks for the info you guys have been super helpful cheers!
